module.exports = {
  LOGINIPC: {
    LOGIN: 'LOGIN',
    CANCELLOGIN: 'CANCELLOGIN',
    OPENDEV: 'OPENDEV',
    CLOSE: 'CLOSE',
    MINIMIZE: 'MINIMIZE'
  },
  INDEXIPC: {
    CLOSE: 'CLOSE',
    GETUSERINFO: 'GETUSERINFO'
  }
}
